spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my_database
    username: my_user
    password: my_password
  jpa:
    hibernate:
      ddl-auto: update